name: device_policy_manager
description: Query Android device Administrator (DevicePolicyManager)
version: 1.0.0
homepage: https://github.com/X-SLAYER/device_policy_manager

environment:
  sdk: '>=2.16.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
          package: device.policy.manager
          pluginClass: DevicePolicyManagerPlugin